POST https://node-fastify-w1q4.onrender.com/videos
Content-Type:  application/json

{
    "title": "Video node",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###
GET https://node-fastify-w1q4.onrender.com/videos
###
PUT https://node-fastify-w1q4.onrender.com/videos/6cde6280-abb3-4ba5-a400-1502ade5f3cd
Content-Type:  application/json

{
    "title": "Video 2",
    "description": "Esse é o vídeo 02",
    "duration": 180
}

###
DELETE https://node-fastify-w1q4.onrender.com/videos/6cde6280-abb3-4ba5-a400-1502ade5f3cd
